server {
    listen 80;
    server_name localhost kittygrm.ddns.net foodgrm.sytes.net 158.160.247.55;

    location /api/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /admin/ {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Статика React (фронтенд) - лежит в /usr/share/nginx/html/static/
    location /static/ {
        alias /usr/share/nginx/html/static/;
    }

    # Статика Django (админка) - лежит в volume /django_static/
    location /django_static/ {
        alias /django_static/;
    }

    location /media/ {
        alias /media/;
    }

    location /api/docs/ {
        root /usr/share/nginx/html;
        try_files $uri $uri/redoc.html;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri /index.html;
    }
}